apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: demo111reg123.azurecr.io/azvote/azure-vote-front
    newTag: 4ca053365656e9b4915c4007056b92d5f593ec72
  - name: demo111reg123.azurecr.io/azvote/azure-vote-back
    newTag: 4ca053365656e9b4915c4007056b92d5f593ec72
resources:
  - manifests.yaml