apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: demo111reg123.azurecr.io/azvote/azure-vote-front
    newTag: b105ad5a0298dfbb5acc54762c8a26fbbbf42a2d
  - name: demo111reg123.azurecr.io/azvote/azure-vote-back
    newTag: b105ad5a0298dfbb5acc54762c8a26fbbbf42a2d
resources:
  - manifests.yaml