apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: stage

images:
  - name: demo111reg123.azurecr.io/azvote/azure-vote-front
    newTag: 7c92a4726552e806bf4421b20a5cebc6bd804222
  - name: demo111reg123.azurecr.io/azvote/azure-vote-back
    newTag: 7c92a4726552e806bf4421b20a5cebc6bd804222
resources:
  - manifests.yaml