apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: stage

images:
  - name: demo111reg123.azurecr.io/azvote/azure-vote-front
    newTag: 3fca341b6c599df2b094bed04794834ba0963618
  - name: demo111reg123.azurecr.io/azvote/azure-vote-back
    newTag: 3fca341b6c599df2b094bed04794834ba0963618
resources:
  - manifests.yaml