apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: stage

images:
  - name: demo111reg123.azurecr.io/azvote/azure-vote-front
    newTag: c4caafa8ab75b1821978b552f92c86310c468b58
  - name: demo111reg123.azurecr.io/azvote/azure-vote-back
    newTag: c4caafa8ab75b1821978b552f92c86310c468b58
resources:
  - manifests.yaml