apiVersion: v1
kind: Service
metadata:
  name: azure-vote-back
  namespace: dev
spec:
  ports:
  - port: 6379
  selector:
    app: azure-vote-back
---
apiVersion: v1
kind: Service
metadata:
  name: azure-vote-front
  namespace: dev
spec:
  ports:
  - port: 80
  selector:
    app: azure-vote-front
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-vote-back
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-vote-back
  template:
    metadata:
      labels:
        app: azure-vote-back
    spec:
      containers:
      - env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        image: demo111reg123.azurecr.io/azvote/azure-vote-back:800ef139b2cecee8eded3eae709ed577ceb67fdb
        name: azure-vote-back
        ports:
        - containerPort: 6379
          name: redis
      nodeSelector:
        beta.kubernetes.io/os: linux
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-vote-front
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-vote-front
  template:
    metadata:
      labels:
        app: azure-vote-front
    spec:
      containers:
      - env:
        - name: REDIS
          value: azure-vote-back
        - name: TITLE
          value: Voting Application
        image: demo111reg123.azurecr.io/azvote/azure-vote-front:800ef139b2cecee8eded3eae709ed577ceb67fdb
        name: azure-vote-front
        ports:
        - containerPort: 80
      nodeSelector:
        beta.kubernetes.io/os: linux
